### ISSUE TITLE
babel

### ISSUE THREAD

**Issue by pedritomelenas** [bvaldivielso/tfg#1]
Utiliza `\usetikzlibrary{babel}` debajo de tikz, y ya podrás usar  `\usepackage[spanish]{babel}` antes para el español. Ya no necesitarás cosas como 
```
\renewcommand{\chaptername}{Capítulo}
```
y cortará las palabras bien.

**Comment by bvaldivielso** [comment]
¡Muchas gracias Pedro!

Creo que ya está arreglado.
